import type { ProductAttributes } from './product.model'

export const seedProducts: Array<Omit<ProductAttributes, 'createdAt' | 'id' | 'updatedAt'>> = [
  {
    category: 'road',
    description:
      'Un pneu route oriente performance, concu pour garder une sensation vive sur les sorties rapides et les longues portions roulantes.',
    eBikeReady: false,
    headline: 'Vitesse et precision pour la route',
    imageUrl: '/images/products/road-race.svg',
    name: 'Velocity Road Race',
    priceFrom: 54,
    sizes: ['700x25', '700x28', '700x30'],
    slug: 'velocity-road-race',
    technologies: ['Grip bi-density', 'Casing 3x120 TPI', 'Race Shield'],
    tubelessReady: true,
    usages: ['Course', 'Route', 'Entrainement intensif'],
  },
  {
    category: 'gravel',
    description:
      'Une bande centrale roulante et des crampons lateraux marques pour passer de la route aux chemins sans changer de rythme.',
    eBikeReady: false,
    headline: 'Ligne rapide, epaulements rassurants',
    imageUrl: '/images/products/gravel-allroad.svg',
    name: 'Gravel Terra Flow',
    priceFrom: 49,
    sizes: ['700x35', '700x40', '700x45'],
    slug: 'gravel-terra-flow',
    technologies: ['Mixed Terrain Grip', 'Puncture Belt', 'Tubeless Ready'],
    tubelessReady: true,
    usages: ['Gravel', 'All road', 'Bikepacking leger'],
  },
  {
    category: 'mtb',
    description:
      'Un profil VTT polyvalent pour garder du controle dans les sentiers techniques, les relances et les descentes engagees.',
    eBikeReady: false,
    headline: 'Controle et motricite sur trail',
    imageUrl: '/images/products/mtb-trail.svg',
    name: 'Wild Trail Grip',
    priceFrom: 59,
    sizes: ['27.5x2.35', '29x2.35', '29x2.50'],
    slug: 'wild-trail-grip',
    technologies: ['Trail Compound', 'Reinforced Bead', 'Sidewall Guard'],
    tubelessReady: true,
    usages: ['All Mountain', 'Trail', 'Enduro leger'],
  },
  {
    category: 'e-bike',
    description:
      'Une carcasse renforcee pour les velos electriques, avec un dessin stable qui privilegie la securite au quotidien.',
    eBikeReady: true,
    headline: 'Renfort et confort pour e-bike',
    imageUrl: '/images/products/ebike-city.svg',
    name: 'E-City Protect',
    priceFrom: 42,
    sizes: ['650x47', '700x45', '27.5x2.00'],
    slug: 'e-city-protect',
    technologies: ['E-Bike Ready', 'Anti-Puncture Layer', 'Reflective Strip'],
    tubelessReady: false,
    usages: ['e-City', 'e-Touring', 'Trajets quotidiens'],
  },
  {
    category: 'city',
    description:
      'Un pneu urbain robuste et confortable, pense pour les trajets reguliers, les pistes cyclables et les routes degradees.',
    eBikeReady: true,
    headline: 'Fiabilite pour la ville',
    imageUrl: '/images/products/city-tour.svg',
    name: 'City Tour Secure',
    priceFrom: 35,
    sizes: ['700x35', '700x40', '26x1.75'],
    slug: 'city-tour-secure',
    technologies: ['Urban Shield', 'Reflective Strip', 'Long Life Rubber'],
    tubelessReady: false,
    usages: ['Urbain', 'Touring', 'Trekking'],
  },
  {
    category: 'kids',
    description:
      'Un pneu enfant simple, resistant et rassurant pour accompagner les premiers trajets, les chemins faciles et les sorties famille.',
    eBikeReady: false,
    headline: 'Pour apprendre en confiance',
    imageUrl: '/images/products/kids.svg',
    name: 'Junior Adventure',
    priceFrom: 19,
    sizes: ['16x1.75', '20x1.75', '24x1.95'],
    slug: 'junior-adventure',
    technologies: ['Durable Rubber', 'Easy Grip'],
    tubelessReady: false,
    usages: ['Enfant', 'Loisir', 'Chemins faciles'],
  },
]
